name: Deploy to Railway

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Railway
        uses: railwayapp/railway-deploy@v1
        with:
          service: semsupdate   # ⚡ replace with your Railway service name
          apiToken: ${{ secrets.RAILWAY_API_KEY }}
